# Generated by Django 5.2 on 2025-05-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='farm_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='farm_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='farm_type',
            field=models.CharField(blank=True, choices=[('Organic', 'Organic'), ('Conventional', 'Conventional')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='documents/id_proofs/'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='ownership_proof',
            field=models.FileField(blank=True, null=True, upload_to='documents/ownership_proofs/'),
        ),
    ]
