# Generated by Django 5.2 on 2025-04-22 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=0.0009559434746467166, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='api.product'),
            preserve_default=False,
        ),
    ]
