# Generated by Django 4.2 on 2025-10-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_ordermodel_paid_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('FARMER', 'Farmer'), ('BUYER', 'Buyer')], default='BUYER', max_length=10)),
            ],
        ),
    ]
